config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('exercise/', include('exercise.urls')),
    path('result/', include('result.urls')),
    path('survey/', include('survey.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exercise/urls.py
from  django.urls import path
from . import views

app_name = "exercise"
urlpatterns = [
    path('get_addr/', views.get_addr, name='get_addr'),
    path('get_locations/', views.get_locations, name='get_locations'),
]

main/urls.py
from  django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.index, name='index'),
]

result/urls.py
from  django.urls import path
from . import views

app_name = "result"
urlpatterns = [
    path('<int:survey_pk>', views.get_result, name='get_result'),
    path('copyright/', views.copyright, name="copyright"),
]

survey/urls.py
from  django.urls import path
from . import views

app_name = "survey"
urlpatterns = [
    path('', views.question, name='question'),
]

exercise/models.py
from django.db import models

# Create your models here.

class Exercise(models.Model):
    name = models.CharField(max_length=200)
    sports = models.CharField(max_length=200)
    addr = models.CharField(max_length=300)
    x_coord = models.FloatField()
    y_coord = models.FloatField()
    tel = models.CharField(max_length=200, blank=True)

main/models.py
from django.db import models

# Create your models here.
class Health(models.Model):
    name_animal = models.CharField(max_length=50)
    name_exercise = models.CharField(max_length=50)
    content = models.CharField(max_length=200, default='hello')

    count = models.IntegerField(default=0)

    def __str__(self):
        return self.name_animal

result/models.py
from django.db import models

# Create your models here.

class BMI(models.Model):
    sex = models.CharField(max_length=10)
    body_mass = models.FloatField()
    age = models.IntegerField()


class Walk(models.Model):
    sex = models.CharField(max_length=10)
    walk_cnt = models.IntegerField()
    age = models.IntegerField()


class Animal(models.Model):
    name = models.CharField(max_length=100)
    content1 = models.CharField(max_length=100)
    content2 = models.CharField(max_length=100)
    animal_num = models.IntegerField()

survey/models.py
from django.db import models
from django.db.models.fields import BooleanField

# Create your models here.
class Survey(models.Model):
    RANKS = [ (1, '10대'), (2, '20대'), (3, '30대'), (4, '40대'), (5, '50대'), (6, '60대'), (7, '70대'), (8, '80대 이상'), ]
    SEXS = [('F', '여자'), ('M', '남자')]
    INDOORS = [(1, '실내'), (0, '실외')]
    ALONES = [(1, '혼자'), (0, '같이')]
    LIGHTS = [(1, '가볍게'), (0, '제대로')]
    age = models.IntegerField(choices=RANKS)
    sex = models.CharField(choices=SEXS, max_length=10)   
    height = models.FloatField()
    weight = models.FloatField()
    walk_cnt = models.IntegerField()
    
    
    indoor = models.IntegerField(choices=INDOORS) 
    alone = models.IntegerField(choices=ALONES) 
    light = models.IntegerField(choices=LIGHTS)  

survey/forms.py
from django import forms
from django.forms import fields
from .models import Survey

class SurveyForm(forms.ModelForm):

    
    class Meta:
        model = Survey
        fields = '__all__'

exercise/views.py
from django.shortcuts import render
from config.settings import API_KEY_MAP

from exercise.models import Exercise

from django.conf import settings

# Create your views here.
def get_addr(request):
    return render(request, 'exercise/get_addr.html')


def get_locations(request):
    my_filter1 = request.POST['data1']
    my_filter2 = request.POST['data2']
    exercises = Exercise.objects.filter(addr__contains=my_filter1).filter(addr__contains=my_filter2)
    API_KEY_MAP = getattr(settings, 'API_KEY_MAP', 'API_KEY_MAP')
    
    context = {
        'exercises': exercises,
        'apiKey': API_KEY_MAP,
    }
    return render(request, 'exercise/get_locations.html', context)

main/views.py
from django.shortcuts import render

from main.models import Health
from survey.models import Survey

from django.conf import settings

# Create your views here.
def index(request):
    healths = Health.objects.all()
    survey_cnt = Survey.objects.all().count()

    API_KEY_SHARE_KAKAO = getattr(settings, 'API_KEY_SHARE_KAKAO', 'API_KEY_SHARE_KAKAO')

    context = {
        'healths': healths,
        'survey_cnt': survey_cnt,
        'api_Key': API_KEY_SHARE_KAKAO,
    }

    return render(request, 'main/index.html', context)

result/views.py
from django.shortcuts import get_object_or_404, render
from survey.models import Survey
from .models import BMI, Walk, Animal
from django.db.models import Avg
import random

from django.conf import settings

EX_LIST = { 
    '111': [('롤러스케이트', '1'), ('헬스', '2')],
    '110': [('피겨', '3'), ('리듬체조', '4'), ('권투', '5')],
    '101': [('농구', '6'), ('에어로빅', '7')],
    '100': [('하키', '8'), ('합기도', '9'), ('태권도', '10')],
    '011': [('롤러스케이트', '1'), ('자전거', '12'), ('조깅', '13'), ('등산', '14')],
    '010': [('사이클', '15'), ('스케이트보드', '16'), ('양궁', '17')],
    '001': [('축구', '18'), ('농구', '6')],
    '000': [('야구', '11'), ('테니스', '20')]
    }


def get_bmi(h, w):
    return round(w / ((h/100) ** 2), 2)


def get_bmi_avg(user_age, user_sex):
    b_avg = BMI.objects.filter(age=user_age, sex=user_sex).aggregate(Avg('body_mass'))
    return round(b_avg['body_mass__avg'], 2)



def get_walkcnt_rank(wc, user_age, user_sex):
    others_walkcnt = Walk.objects.filter(age=user_age, sex=user_sex).order_by('-walk_cnt')
    rank = 1
    for other in others_walkcnt:
        if other.walk_cnt < wc:
            break
        rank += 1
    return rank, others_walkcnt.count() + 1



def get_walkcnt_avg(user_age, user_sex):
    wc_avg = Walk.objects.filter(age=user_age, sex=user_sex).aggregate(Avg('walk_cnt'))
    return round(wc_avg['walk_cnt__avg'], 2)



def exercise_recommend(user_indoor, user_alone, user_light):
    tmp = ''
    tmp += str(user_indoor) +str(user_alone) + str(user_light)
    return random.choice(EX_LIST[tmp])


def get_animal_id(wc_percent):
    if wc_percent >= 80:
        return '5'
    elif wc_percent >= 60:
        return '4'
    elif wc_percent >= 40:
        return '3'
    elif wc_percent >= 20:
        return '2'
    else:
        return '1'


def get_result(request, survey_pk):

    survey = get_object_or_404(Survey, pk=survey_pk)
    exercise, exercise_id = exercise_recommend(survey.indoor, survey.alone, survey.light)

    user_bmi = get_bmi(survey.height, survey.weight)

    bmi_avg = get_bmi_avg(survey.age, survey.sex)


    user_wc_rank, wc_data_cnt = get_walkcnt_rank(survey.walk_cnt, survey.age, survey.sex)
    user_wc_rate = round(user_wc_rank / wc_data_cnt * 100, 2)
    walkcnt_avg = get_walkcnt_avg(survey.age, survey.sex)

    bmi_gap = round(abs(user_bmi - bmi_avg), 2)

    animal_id = get_animal_id(user_wc_rate)
    animal = Animal.objects.get(animal_num=animal_id)


    API_SHARE_KAKAO = getattr(settings, 'API_KEY_SHARE_KAKAO', 'API_KEY_SHARE_KAKAO')

    context = {
        'survey': survey,

        'animal_id': animal_id,
        'animal': animal,

        'user_bmi': user_bmi,
        'bmi_avg': bmi_avg,
        'bmi_gap': bmi_gap,
        'user_wc_rate': user_wc_rate,
        'walkcnt_avg': walkcnt_avg,

        'exercise':exercise,
        'exercise_id': exercise_id,
        
        'apiKey': API_SHARE_KAKAO,
    }
    return render(request, 'result/result.html', context)


def copyright(request):
    return render(request, 'result/copyright.html')

survey/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .models import Survey
from .forms import SurveyForm



@require_http_methods(['GET', 'POST'])
def question(request):
    if request.method == 'POST':
        form = SurveyForm(request.POST)
        if form.is_valid():
            survey = form.save()
            return redirect('result:get_result', survey.pk)
    else:
        form = SurveyForm()
    context  = {
        'form': form,
    }
    return render(request, 'survey/question.html', context)

exercise/templates/exercise/get_addr.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script type="text/javascript" src="{% static 'js/get_addr.js' %} "></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/addr_style.css' %}">

    <title>뿌셔 테스트</title>
</head>
<body>
    <section id="main_contents">
      <div class="wrapper container">
        <h1>주소를 입력하세요</h1>

        <form action="{% url 'exercise:get_locations' %}" method="POST" name="addr_form">
            {% csrf_token %}
            <div class="container sub-container">
                <input type="text" id="address_kakao" name="address" placeholder="Click Me!">
                <input type="text" id="data1" name="data1" class="my-data">
                <input type="text" id="data2" name="data2" class="my-data">
                <div class="btn_wrap">
                    <a href="{% url 'main:index' %}">
                        <button id="main_btn" type="button">Main</button>
                    </a>
                    <button id="go_btn" class="next_btn_input" onclick="check_input()">Next</button>
                </div>
            </div>
        </form>
      </div>
    </section>
</body>
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
window.onload = function(){
    document.getElementById("address_kakao").addEventListener("click", function(){ 
        
        new daum.Postcode({
            oncomplete: function(data) { 
                document.getElementById("address_kakao").value = data.address; 
                document.getElementById("data1").value = data.sigungu; 
                document.getElementById("data2").value = data.bname; 
                console.log(data)
            }
        }).open();
    });
}
</script>
</html>

exercise/templates/exercise/get_locations.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/locations_style.css' %}">

  <title>뿌셔 테스트</title>
</head>
<body>
  <section id="main_contents">
    <div class="wrapper">
      <div class="btn_wrap">
        <a href="{% url 'exercise:get_addr' %}">
          <button type="button">Back</button>
        </a>
      </div>
      <div class="title">
        <h1 class="main_title">운동 시설 목록</h1>
        <p class="sub_title">운동시설 개수 : {{ exercises.count }}</p>
      </div>
      <div class="intro">
        {% for exercise in exercises %}
          <p>{{ exercise.sports }}</p>
          <p>{{ exercise.addr }}</p>
          <p>{{ exercise.name }} </p>
          <div class="modal modal-{{ exercise.pk }}">
            <div class="modal_body modal-body-{{ exercise.pk }}">
              <div id="map-{{ exercise.pk }}" style="width:100%;height:350px;"></div>
              <button class="close-btn-{{ exercise.pk }}">닫기</button>
            </div>
          </div>
          <form class="modal-open-form" data-pk="{{ exercise.pk }}" data-y="{{ exercise.y_coord }}" data-x="{{ exercise.x_coord }}" data-name="{{ exercise.name }}">
            <button class="btn-open-popup-{{ exercise.pk }}">지도보기</button>
          </form>
          <hr>
        {% endfor %}
      </div>
    </div>
  
  </section>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey={{apiKey}}"></script>
  <script>
    const forms = document.querySelectorAll('.modal-open-form')
    forms.forEach(function (form) {
      form.addEventListener('submit', function (event) {
        event.preventDefault()

        const pk = form.dataset.pk
        const y_idx = form.dataset.y
        const x_idx = form.dataset.x
        const name = form.dataset.name

        const modal = document.querySelector(`.modal-${pk}`)
        modal.classList.toggle('show');

        const cls_btn = document.querySelector(`.close-btn-${pk}`)
        cls_btn.addEventListener('click', () => {
          modal.classList.remove('show')
        })

        modal.addEventListener('click', (event) => {
          if (event.target === modal) {
            modal.classList.toggle('show');
          }
        })

        var mapContainer = document.getElementById(`map-${pk}`),
        mapOption = { 
            center: new kakao.maps.LatLng(y_idx, x_idx),
            level: 3
        };

        var map = new kakao.maps.Map(mapContainer, mapOption);

        var markerPosition  = new kakao.maps.LatLng(y_idx, x_idx);

        var marker = new kakao.maps.Marker({
            position: markerPosition
        });

        marker.setMap(map);
        var iwContent = `<div style="padding:5px;">
            <div>${name}</div>
            <a href="https://map.kakao.com/link/map/${name},${y_idx},${x_idx}"
            style="color:blue" target="_blank">큰지도보기</a>
            <a href="https://map.kakao.com/link/to/${name},${y_idx},${x_idx}" style="color:blue" target="_blank">길찾기</a></div>`
            iwPosition = new kakao.maps.LatLng(33.450701, 126.570667);

        var infowindow = new kakao.maps.InfoWindow({
          position : iwPosition, 
          content : iwContent 
        });
        infowindow.open(map, marker); 
      })
    })

  </script>
</body>
</html>

main/templates/main/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>뿌셔 테스트</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script type="text/javascript" src="{% static 'js/main.js' %} "></script>
  <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
</head>
<body>
    <section id="main_contents">
    <div class="wrapper">
      <div class="title">
        <h3 class="main_title">나의 건강 유형은</h3>
        <h3 class="sub_title">어떤걸까?</h3>
      </div>
      <div class="intro">
        <div class="type">
          <ul class="type_list">
            <li>나무늘보</li>
            <li>코모도 도마뱀</li>
            <li>코끼리</li>
            <li>황제 펭귄</li>
            <li>바나나 민달팽이</li>
          </ul>
        </div>
      </div>
      <div class="button">
        <a href="{% url 'survey:question' %}">
          <button class="start" type="button">start</button>
        </a>
        <a href="{% url 'exercise:get_addr' %}">
          <button class="start" type="button">체육 시설 알아보기</button>
        </a>
      </div>
      <div class="share">
        <div class="content">
          <a href="javascript:copyUrl()" title="linkcopy"> 
            <img src="{% static 'image/link_icon.png' %}" width=50 alt="linkcopy">
          </a>
          <a href="javascript:sharefacebook()" title="facebookshare">
            <img src="{% static 'image/facebook_icon.png' %}" width=50 alt="Facebook">
          </a>
          {% comment %} <a href="javascript:sendLink()" title="kakaoshare">
            <img src="{% static 'image/kakao_icon.png' %}" width=50 alt="kakao">
          </a> {% endcomment %}
          {% comment %} <a id="create-kakao-link-btn" href="javascript:;">
            <img src="https://developers.kakao.com/assets/img/about/logos/kakaolink/kakaolink_btn_medium.png" width=50>
          </a> {% endcomment %}
          {% comment %} <button type="button" class="kakao_share">
            <img src="{% static 'image/kakao_icon.png' %}" width=50 alt="kakao">
          </button> {% endcomment %} 
          {% comment %} <div class="kakao-link"> <a id="kakao-link-btn" href="#" onclick="sendLink"> 카카오톡으로 공유하기 </a> </div> {% endcomment %}
          {% comment %} <div class="kakao-link"> <button id="kakao-link-btn" onclick="kakaoLink"> 카카오톡으로 공유하기 </button> </div> {% endcomment %}
        </div>
      </div>

      <div class="result_data">
        <div class="data_wrap">
          <h3>참여한 사람</h3>
          <ul>

            <li class="cnt_style">{{ survey_cnt }}</li>
          </ul>
        </div>
      </div>
      <div class="project_pyh">
        <a href="https://github.com/Data-study-project">
          <img src="{% static 'image/data_logo.png' %} " alt="logo">
        </a>
      </div>
    </div>
  </section>
</body>
{% comment %} {% block js %}
  <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script type="text/javascript" src="{% static 'js/main.js' %} "></script>
{% endblock js %}  {% endcomment %}
<script type="text/javascript">
  Kakao.init('{{api_key}}');
  console.log(Kakao.isInitialized());
    Kakao.Link.createDefaultButton({
    container: '#create-kakao-link-btn',
    objectType: 'feed',
    content: {
      title: '딸기 치즈 케익',
      description: '#케익 #딸기 #삼평동 #카페 #분위기 #소개팅',
      imageUrl:
        'http://k.kakaocdn.net/dn/Q2iNx/btqgeRgV54P/VLdBs9cvyn8BJXB3o7N8UK/kakaolink40_original.png',
      link: {
        mobileWebUrl: 'https://ppusyeo.herokuapp.com',
        webUrl: 'https://ppusyeo.herokuapp.com',
      },
    },
    social: {
      likeCount: 286,
      commentCount: 45,
      sharedCount: 845,
    },
    buttons: [
      {
        title: '웹으로 보기',
        link: {
          mobileWebUrl: 'https://ppusyeo.herokuapp.com',
          webUrl: 'https://ppusyeo.herokuapp.com',
        },
      },
      {
        title: '앱으로 보기',
        link: {
          mobileWebUrl: 'https://ppusyeo.herokuapp.com',
          webUrl: 'https://ppusyeo.herokuapp.com',
        },
      },
    ],
  })
  {% comment %} Kakao.Link.sendDefault({
    container: '#create-kakao-link-btn',
    objectType: 'feed',
    content: {
      title: '나의 건강 상태는?',
      description: '나의 현재 건강 상태는 어떨까?',
      imageUrl: 'https://ppusyeo.herokuapp.com/', 
      link: {
        mobileWebUrl: 'https://ppusyeo.herokuapp.com/',
        webUrl: 'https://ppusyeo.herokuapp.com/',
      },
    },
  }) {% endcomment %}


  /*
  Kakao.Link.createScrapButton({
    container: '#create-kakao-link-btn',
    requestUrl: 'https://ppusyeo.herokuapp.com',
  })*/
</script>
{% comment %} 
<script type="text/javascript">
console.log({{apiKey}}) 
kakao.init({{apiKey}});
function sendLink() {
  console.log({{apiKey}})
  Kakao.Link.sendDefault({
    //container: '#kakao-share',
    objectType: 'feed',
    content: {
      title: '나의 건강 상태는?',
      description: '나의 현재 건강 상태는 어떨까?',
      imageUrl: 'https://ppusyeo.herokuapp.com/', 
      link: {
        mobileWebUrl: 'https://ppusyeo.herokuapp.com/',
        webUrl: 'https://ppusyeo.herokuapp.com/',
      },
    },
    
    social: {
      likeCount: 100,
      commentCount: 10,
      sharedCount: 100,
    },
    buttons: [
      {
        title: '결과 확인하기',
        link: {
          webUrl: result_url,
          mobileWebUrl: result_url,
        },
      },
      {
        title: '테스트 해보기',
        link: {
          webUrl: 'https://ppusyeo.herokuapp.com/',
          mobileWebUrl: 'https://ppusyeo.herokuapp.com/',
        },
      },
    ]
  });

};
</script> {% endcomment %}
</html>

result/templates/result/result.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta property="og:title" content="나의 건강 상태는?" />
  <meta property="og:image" content="" />
  <meta property="og:url" content="" />
  <meta property="og:description" content="나의 건강 상태는 현재 어떨까?" />

  <script type="text/javascript" src="{% static 'js/result.js' %} "></script>
  <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
  
  <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/result.css' %}">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>

  <title>뿌셔 테스트</title>
</head>
<body>
  <section id="main_contents">
    <div class="wrapper">
      <div class="result">
        <div class="titles">
          <h3>당신의 하루 이동량과 닮은 동물은?</h3>
          <h1>{{ animal.name }}</h1>
        </div>
        <div class="result_img">
          <img src="{% get_static_prefix  %}image_animals/{{animal_id}}.png" alt="animal img">
        </div>
      </div>
      <div class="result_explains">
        <div class="explain">
          <h3 class="title">{{ animal.name }}의 특징은?</h3>
          <ul>
            <li>{{ animal.content1 }}</li>
            <li>{{ animal.content2 }}</li>
          </ul>
        </div>
        <div class="explain">
          <h3 class="title">나의 운동 능력은</h3>
          <div style="width: 400px; height:300px;">
            <canvas id="walk"></canvas>
          </div>
          <div style="width: 400px; height:300px;">
            <canvas id="bmi"></canvas>
          </div>
          <ul>
            <li>하루 걸음수는 {{ survey.age }}0대 
              {% if survey.sex == "M" %}
                남자
              {% else %}
                여자
              {% endif %}
              중 상위 <span class="bold">{{ user_wc_rate }}%</span> 입니다!</li>
            <li>당신의 나이와 성별기준 평균 BMI는 <span class="bold">{{ bmi_avg }}</span> 입니다!</li>
            <li>당신의 BMI는 평균보다
              {% if user_bmi > bmi_avg %}
                약 <span class="bold">{{ bmi_gap }}</span>만큼 높습니다.
              {% else %}
                약 <span class="bold">{{ bmi_gap }}</span>만큼 낮습니다.
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
      <div class="exercises">
        <h3 class="title">당신을 위한 운동 추천</h3>
          <ul>
            <li>
              <a href="#" target="_blank">
                <img src="{% get_static_prefix %}image_sports/{{exercise_id}}.png" alt="exercise img">
                <h3>{{ exercise }}</h3>
              </a>
            </li>
          </ul>
      </div>
      <div class="buttons">
        <ul>
          <li>
            <a href="{% url 'exercise:get_addr' %}">
              <button type="button">주변 운동 시설</button>
            </a>
          </li>
          <li>
            <a href="{% url 'main:index' %}">
              <button type="button">테스트 다시하기</button>
            </a>
          </li>

        </ul>
      </div>
      <div class="share">
        <div class="content">
          <a href="javascript:copyUrl()" title="linkcopy"> 
            <img src="{% static 'image/link_icon.png' %}" width=50 alt="linkcopy">
          </a>
          <a href="javascript:sharefacebook()" title="facebookshare">
            <img src="{% static 'image/facebook_icon.png' %}" width=50 alt="Facebook">
          </a>
          {% comment %} <a href="javascript:sendLink()" title="kakaohare">
            <img src="{% static 'image/kakao_icon.png' %}" width=50 alt="kakao">
          </a> {% endcomment %}
        </div>
      </div>
      <div class="project_pyh">
        <a href="https://github.com/Data-study-project">
          <img src="{% static 'image/data_logo.png' %}" width=50 alt="logo">        </a>
      </div>
      
      <div>
      <a href="{% url 'result:copyright' %}">copyright</a>
      </div>
      
    </div>

  </section>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script>
  const ctx1 = document.getElementById('walk').getContext('2d');
  const walk = new Chart(ctx1, {
      type: 'bar',
      data: {
          labels: ['당신의 걸음 수', '평균 걸음 수'],
          datasets: [{
              type: 'bar',
              label: 'bar Dataset',
              data: [{{ survey.walk_cnt }}, {{ walkcnt_avg }}],
              backgroundColor: [
                  'rgba(255, 99, 132)',
                  'rgba(54, 162, 235)',
              ],
              order: 2
          }, {
              label: 'Line Dataset',
              data: [{{ survey.walk_cnt }}, {{ walkcnt_avg }}],
              type: 'line',
              order: 1
          }]
      },
      options: {
        plugins: {
          legend: {
            display: false
          },
        },
        scale: {
          ticks: {
              display: false
          }
        }
      }
  });


  const ctx2 = document.getElementById('bmi').getContext('2d');
  const bmi = new Chart(ctx2, {
      data: {
          labels: ['당신의 bmi', '평균 bmi'],
          datasets: [{
              type: 'bar',
              label: 'bar Dataset',
              data: [{{ user_bmi }}, {{ bmi_avg }}],
              backgroundColor: [
                  'rgba(255, 99, 132)',
                  'rgba(54, 162, 235)',
              ],
              order: 2

          }, {
              label: 'Line Dataset',
              data: [{{ user_bmi }}, {{ bmi_avg }}],
              type: 'line',
              order: 1
          }]
      },
      options: {
        plugins: {
          legend: {
            display: false
          },
        scale: {
          ticks: {
            display: false
            }
          },
        }
      }
  });


</script>

<script>kakao.init('{{apiKey}}');</script>
<script>
function sendLink() {
  let result_url = window.location.href;
  Kakao.Link.sendDefault({
    objectType: 'feed',
    content: {
      title: '나의 건강 상태는?',
      description: '나의 현재 건강 상태는 어떨까?',
      imageUrl:
        '',
      link: {
        mobileWebUrl: 'https://ppusyeo.herokuapp.com/',
        webUrl: 'https://ppusyeo.herokuapp.com/',
      },
    },
    social: {
      likeCount: 100,
      commentCount: 10,
      sharedCount: 100,
    },
    buttons: [
      {
        title: '결과 확인하기',
        link: {
          webUrl: result_url,
          mobileWebUrl: result_url,
        },
      },
      {
        title: '테스트 해보기',
        link: {
          webUrl: 'https://ppusyeo.herokuapp.com/',
          mobileWebUrl: 'https://ppusyeo.herokuapp.com/',
        },
      },
    ]
  });

};
</script>
</body>
</html>